baseURL = "https://thinkindawn.pages.dev"
defaultContentLanguage = "zh-cn"
theme = "DoIt"
title = "魏忽歌平旦随想"

# 是否使用 robots.txt
enableRobotsTXT = true
# 是否使用 git 信息
enableGitInfo = true
# 是否使用 emoji 代码
enableEmoji = true

# 忽略一些构建错误
# ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]